### ISSUE TITLE
Grant-Access flow failing

### ISSUE THREAD

**Issue by diego-cocacola** [jenschristianschroder/JIT-Access-Management#29]
Testing the JIT App I'm getting this error when running the Grant-Access flow:

Http request failed as there is an error getting AD OAuth token: 'AADSTS700016: Application with identifier 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' was not found in the directory 'Contoso'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: 2d61dd77-aca3-44ff-86cc-f700e17a9901
Correlation ID: 586635ab-e714-4e16-a955-3d4c66009706
Timestamp: 2023-05-30 19:31:55Z'.

here is a screenshot of the action that failed:

![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/133714338/4fad5377-b9ca-4856-a32e-ead04daafdc0)

could this be related to the tenant hardcoded?

**Comment by jenschristianschroder** [comment]
Yes! Could very well be.

Thanks for trying it out and reporting this. Very much appreciated! 

I will fix this in a new release.

**Comment by diego-cocacola** [comment]
don't mention it, thanks to you for this great feature! will be heavily used in our organization :)

**Comment by jenschristianschroder** [comment]
I've added a Tenant field to the setup record.

You can get the release here: https://github.com/jenschristianschroder/JIT-Access-Management/releases/tag/v1.0.20230530.4-PREVIEW

You should set that to either tenant id or domain name.

Please let me know any other issues you might find.

**Comment by diego-cocacola** [comment]
![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/133714338/d5961031-7f7a-4388-acb0-7c3459e0ae6a)

looks like it is working now 😊, will perform more tests tomorrow, thanks again for this!
