### ISSUE TITLE
Label width in Access Profile

### ISSUE THREAD

**Issue by MrHueb** [jenschristianschroder/JIT-Access-Management#38]
The label width in the access profile gallery of the canvas application is too narrow to display the text.
Consider increasing width. Limiting the column max. string length is probably a bad idea as admins will want to give the very discriptive names.
![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/56923538/b15be4b6-d7b9-4dd9-be99-afdb4a497fa1)

**Comment by jenschristianschroder** [comment]
Thanks for reporting this.

Will consider ways to fix this an implement in future release

**Comment by jenschristianschroder** [comment]
This is the fix that will be included in next release. When is TBD but should be fairly soon :)

The title will not exceed the tile. The text will be shortened if it exceeds the tile. On Hover will show the full title
![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/24893229/daf74f6b-5fed-4aad-918a-e86801ecfaad)

**Comment by jenschristianschroder** [comment]
Fixed in https://github.com/jenschristianschroder/JIT-Access-Management/releases/tag/v1.0.20230606.1
