### ISSUE TITLE
CANVAS APP // Notify "SELECT" when clicking on Request row

### ISSUE THREAD

**Issue by allandecastro** [jenschristianschroder/JIT-Access-Management#40]
Hello,

Excellent application combining different components to solve a real problem :)

Not a big deal but there is a Notify statement when we click on a row of the Request detail list:

![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/9749002/6162757f-e977-4c79-8bfe-34eaad4cd4f8)

**Comment by jenschristianschroder** [comment]
Hi @allandecastro,

Thank you! Glad you find it useful.

This has been fixed in latest release.
