### ISSUE TITLE
Restrict profiles by users/groups

### ISSUE THREAD

**Issue by diego-cocacola** [jenschristianschroder/JIT-Access-Management#46]
Can you implement a mechanism to enable profiles only  to specific users/groups so users won't be able to see all profiles by default?

**Comment by jenschristianschroder** [comment]
Hi @diego-cocacola ,

Thank you for your suggestion. It's a good idea and something that others have asked for also.

Best approach would be to use the built in features for data sharing.

Today the user security role gives access to all access profiles. Will look at updating it to support your scenario and also look at documenting how to use this feature.

Please keep feedback like this coming!

Thanks

**Comment by jenschristianschroder** [comment]
Hi @diego-cocacola,

The latest release restricts users from request access via profiles unless they are shared with the user or a team the user is in.

For details on how to share records please see the official docs here: https://learn.microsoft.com/en-us/power-apps/user/share-row

Would love your feedback on this :)
