### ISSUE TITLE
Setup Guide: Edit Suggestion

### ISSUE THREAD

**Issue by SPMush** [jenschristianschroder/JIT-Access-Management#67]
Hi Jens
Step 2 of the Configure Access Profile Approval Process had me looking for a few mins can I suggest editing to :

"2. Click the AccessProfile>Approval>Enable Profile button in the command bar." 

![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/55295944/7b3d44db-a210-4df0-b252-206c67e6a9e8)

![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/55295944/cf2259c4-ae05-4d36-bf80-54abe462ea69)
![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/55295944/07495723-6143-49f0-af36-a7ac6eb877e1)

**Comment by jenschristianschroder** [comment]
Thank you!

In a recent release all custom command bar buttons was grouped into the Access Profile button.

Will update the Readme instructions to reflect that change.

**Comment by jenschristianschroder** [comment]
I have updated the instructions with the changes to the command bar button and also removed a couple of steps that are not required.
