### ISSUE TITLE
[Feature Request] A wish list 

### ISSUE THREAD

**Issue by SPMush** [jenschristianschroder/JIT-Access-Management#68]
Hi Jens,
Some feature suggestions.
1. Access Request Overview Page - On Granted requests, display a countdown timer indicating time until access revoked.
2. Access Request - Option so request immediate access or requester can specify a start time/date for the required access window.
3. Access request - "Your request has been Submitted" Feedback after click request access.
4. Generate a log of user committed change actions within the environment during the approved access session and attach to access request record.
5. Access request - Related Support ticket reference number text field.
6. Access request Management - Revoke button for active granted Access request.

Best regards

Matt

**Comment by jenschristianschroder** [comment]
Thank you Matt! I really like these suggestions.

I will split them into individual issues for better tracking and collaboration.

**Comment by jenschristianschroder** [comment]
Hi @SPMush,

I've converted your wish list to individual issues for better tracking :)

I need some help on #72 .

I don't think it is possible to implement until the platform introduce some sort of change tracking on component level.

As for #74  I'm happy to say that this is already a feature. It is available via the Revoke Access command bar button that is displayed on the Access Request if the Status Reason is Granted
![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/24893229/a3ae078e-c863-4a93-9c53-618660c037af)
