### ISSUE TITLE
[Feature Request] Log changes in target environment

### ISSUE THREAD

**Issue by jenschristianschroder** [jenschristianschroder/JIT-Access-Management#72]
Generate a log of user committed change actions within the environment during the approved access session and attach to access request record.

See #68

**Comment by jenschristianschroder** [comment]
My understanding of the feature request is that the solution should capture a log of all change that a maker is doing in the environment for which they were granted access. 
Changes could be anything a Maker can do such as create entity, change field configuration, modify security roles etc.

I don't see how this is possible to implement. It would require that there is some mechanism in the environment that track all changes a Maker is doing. That doesn't exist as far as I'm aware.

If anyone has thoughts and ideas on this please leave a comment

**Comment by SPMush** [comment]
I briefly looked at creating custom reports from Audit Logs. Wondering still if the suggestion is possible, or worth the effort when there are existing mechanisms in Purview for specific query auditing. 

[Microsoft Purview audit log activities via O365 Management API - Part 1](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/microsoft-365-compliance-audit-log-activities-via-o365/ba-p/2957171)
[Microsoft Purview audit log activities via O365 Management API - Part 2](https://techcommunity.microsoft.com/t5/security-compliance-and-identity/microsoft-365-compliance-audit-log-activities-via-o365/ba-p/2957297)

**Comment by jenschristianschroder** [comment]
As there are existing mechanisms to audit data changes in Dataverse and it currently not being possible to track changes across all/most components in an environment, I will close this issue.
