### ISSUE TITLE
Access Profile Shared With Error

### ISSUE THREAD

**Issue by andrewgaskins** [jenschristianschroder/JIT-Access-Management#83]
Hi Jens,

Recently the shared with functionality has been failing. I am getting an error about the app registration. It appears that the http connector in the associated flow is not getting the secret. The profile is showing up for the user but when a request is made everything is in the request except for the user. 

Thanks!
Andrew

Retrieve-Shared-Access.Run failed: { "error": { "code": 502, "source": "unitedstates-002.azure-apim.net", "clientRequestId": "xxxxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxx", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08585070392234518897265260702CU98'." } } } }

**Comment by jenschristianschroder** [comment]
Hi @andrewgaskins,

Sorry for not replying sooner.

Is this still happening? I would love to have a screen share session to understand more. Will reach out to you via other channel to set it up.

Thanks!
Jens

**Comment by jenschristianschroder** [comment]
@andrewgaskins, I'm closing this issue based on our conversation during our call
