### ISSUE TITLE
[BUG] Access Request Approvals not being updated

### ISSUE THREAD

**Issue by lingutla123** [jenschristianschroder/JIT-Access-Management#86]
Hi,

Though environment access request is approved by all and granted the access, system is not showing as approval completed. Please see the attached screenshot where it is showing as "waiting for ..." with grey icon though approval completed. 

Why is this happening? 

![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/126264610/beaa4028-9f9c-4318-8c3e-0ec532cfe2ff)

**Comment by jenschristianschroder** [comment]
Hi @lingutla123,

Thank you for reporting this. 

Can you check if the Start-Access-Request-Approval flow has failed?

**Comment by lingutla123** [comment]
Hi Jen,

No. Start-Access-Request-Approval flow ran successful. But in the condition step the Expression result  is " false".
![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/126264610/1f2865bb-1594-429b-a3f5-705033ac28da)

**Comment by jenschristianschroder** [comment]
Hi @lingutla123,

Can you share a screenshot with the right (If no) path expanded? Within the Apply to each 8 is an Apply to each 9. This is were the activities are updated. If you can share a screenshot of that it would be helpful.

Thanks

**Comment by lingutla123** [comment]
Here is the screen shot.
![image](https://github.com/jenschristianschroder/JIT-Access-Management/assets/126264610/1f2128ab-7158-47d2-81f1-213f62222438)

**Comment by jenschristianschroder** [comment]
This looks to be a bug. The flow uses the display name of the Approver to match to activity records. 
For some reason this is not working in your setup. 

This implementation is not ideal so will look at changing this to match Approvers on Entra Id (Azure Activer Directory ID). This should fix your issue and also be a much better solution as Entra Ids are unique and display names are not.

Thanks for reporting this!

I will update this thread when a new release is available with a fix for this issue!

**Comment by jenschristianschroder** [comment]
Hi @lingutla123,

There is a new release available, v1.0.20231219.1 PREVIEW which include a fix for this bug.

Get the latest release here: https://github.com/jenschristianschroder/JIT-Access-Management/releases

Thank you for reporting this and helping me improve the JIT Access Management solution!

**Comment by lingutla123** [comment]
Thank you.
